position=top-right
table_columns=2
width=280

fps
frametime
frame_timing

gpu_stats
gpu_temp
gpu_power
gpu_core_clock
gpu_mem_clock

cpu_stats
cpu_temp
cpu_power

ram

background_alpha=0.5
font_size=20
toggle_hud=Shift_R+F12
