{
  inputs,
  ...
}:

{
  # Use latest commit's message for the nixos generation label in the boot menu.
  # Since flakes currently still don't support accessing env variables in pure mode,
  # we read the last commit hash from a file generated by a pre-commit hook.
  # TODO: Remove this once flakes support env variables or if flake is removed and `npins` is used instead.
  system.nixos.label = builtins.trace (builtins.readFile (inputs.last-commit-message)) (
    builtins.readFile (inputs.last-commit-message)
  );
}
